services:
    zoddo_ovh.api:
        class: Zoddo\OvhBundle\OvhApi
        arguments:
            - "%zoddo_ovh.api.key%"
            - "%zoddo_ovh.api.secret%"
            - "%zoddo_ovh.api.endpoint%"
            - "@=container.hasParameter('zoddo_ovh.api.ckey') ? parameter('zoddo_ovh.api.ckey') : null"

    ovh.api:
        alias: zoddo_ovh.api