services:
    ovh.api:
        class: Zoddo\OvhBundle\OvhApi
        arguments:
            - "%ovh.key%"
            - "%ovh.secret%"
            - "%ovh.endpoint%"
            - "@=container.hasParameter('ovh.ckey') ? parameter('ovh.ckey') : null"

    ovh:
        alias: ovh.api